name: Build Packages

on: 
  release:
    types: [published]
    
#  push:
#    branches: 
#      - master

# 点赞触发
  watch:
    types: [started]

jobs:
  build_packages:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: 校验本地文件
      uses: actions/checkout@main

    - name: 克隆源代码
      run: |
        df -hT $PWD
        git clone --depth=1 https://github.com/jerrykuku/luci-app-vssr

    - name: 下载sdk
      run: |
        df -hT $PWD
        wget https://downloads.openwrt.org/releases/19.07.5/targets/x86/64/openwrt-sdk-19.07.5-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        tar -xf openwrt-sdk-19.07.5-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz
        ln -sf $PWD/luci-app-vssr/packages/openwrt $PWD/openwrt-sdk-19.07.5-x86-64_gcc-7.5.0_musl.Linux-x86_64/package/luci-app-ssr-plus
        
    - name: 编译ipk
      run: |
        cd openwrt-sdk-19.07.5-x86-64_gcc-7.5.0_musl.Linux-x86_64
        make defconfig
        make package/luci-app-vssr/compile V=s -j$(nproc)
        cp $(find . -name luci-app-vssr_*.ipk) ../

    - name: 上传ipk到 WeTransfer
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ./luci-app-vssr_*.ipk 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"